services:
  webserver56:
    container_name: WSDD-Web-Server-PHP5.6
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WEBMIN_VERSION: __WSDD_WEBMIN_VERSION__
        WEBMIN_USER: __WSDD_WEBMIN_USER__
        WEBMIN_PASS: __WSDD_WEBMIN_PASS__
    restart: always
    expose:
      - "80"   # Exposes Web Server (Apache)
      - "9000" # Exposes xDebug
      - "10000" # Exposes Webmin
    networks:
      - wsdd-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "wsdd.webserver.description=Web Server php5.6"
      - "wsdd.webserver.role=webserver"
    privileged: true
    tty: true

networks:
  wsdd-network:
    external: true
