file_uploads = on
upload_max_filesize = 512M
max_file_uploads = 100
allow_url_fopen = on
memory_limit = 512M
post_max_size = 512M
max_execution_time = 3600
max_input_time = 3600
max_input_vars = 3600
error_reporting = E_ALL
display_errors = on
display_startup_errors = on
html_errors = on
session.gc_maxlifetime = 2592000
session.cache_expire = 2592000