### DO NOT TOUCH ###
ServerName localhost74
<VirtualHost *:80>
    ServerName php74.wsdd.dock
    DocumentRoot /var/www/html/dev
	Protocols h2 h2c http/1.1
    <Directory /var/www/html/dev>
        Options Indexes FollowSymLinks Includes ExecCGI
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog /var/www/html/log/php74.wsdd.dock_error.log
    CustomLog /var/www/html/log/php74.wsdd.dock_access.log combined
</VirtualHost>
<VirtualHost *:80>
    ServerName cron74.wsdd.dock
    Protocols h2 h2c http/1.1
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/
    ProxyPreserveHost On
    <Proxy *>
        Allow from all
    </Proxy>
	ErrorLog /var/www/html/log/cron74.wsdd.dock_error.log
    CustomLog /var/www/html/log/cron74.wsdd.dock_access.log combined
</VirtualHost>
<VirtualHost *:80>
    ServerName wm74.wsdd.dock
    Protocols h2 h2c http/1.1
    ProxyPass / http://127.0.0.1:10000/
    ProxyPassReverse / http://127.0.0.1:10000/
    ProxyPreserveHost On
    <Proxy *>
        Allow from all
    </Proxy>
	ErrorLog /var/www/html/log/wm74.wsdd.dock_error.log
    CustomLog /var/www/html/log/wm74.wsdd.dock_access.log combined
</VirtualHost>
### DO NOT TOUCH ###
### PERSONAL PROJECTS ###
### PERSONAL PROJECTS ###
