[alias]
wix-msi = "wix -p wsdd --target x86_64-pc-windows-msvc"

[build]
# Target principal: Windows x64
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
# Linker por defecto para MSVC
rustflags = ["-C", "target-feature=+crt-static"]
